name: python 3.8
channels:
  - conda-forge
dependencies:
  - python==3.8
  - numpy
  - matplotlib
  - control
  - sympy
  - lxml
  - xlrd
  - networkx
  - pip
  - pip:
    - svgpathtools
    - datetime
    - BondGraphTools
